### ISSUE TITLE
getHeaders() returns wrong data

### ISSUE THREAD

**Issue by dikderoy** [hackerone/curl#10]
on my configuration $curl->getHeaders() returns wrong data.

this is happens because in $this->response (where you are storing response data)
contained something like this:

```
HTTP 100 Continue
\r\n\r\n
HTTP 100 Continue
\r\n\r\n
HTTP 200 OK
<..other headers..>
\r\n\r\n
<..body..>
```

solution is to rewrite getHeaders as following:

``` php5
$responseEntries=explode("\r\n\r\n",$this->response);
$countRE = count($responseEntries);
$headerText = $responseEntries[$countRE-2];
$headers     = array();
foreach (explode("\r\n", $headerText) as $i => $line) {
   if ($i === 0) {
    $headers['http_code'] = $line;
   } else {
    list ($key, $value) = explode(': ', $line);
    $headers[$key] = $value;
   }
}
return $headers;
```

**Comment by dikderoy** [comment]
Over the internet people also saying what explicitly setting an Expects header will also solve this issue, but not all services are working correctly with such solution

**Comment by hackerone** [comment]
could you please add what your exepected header is and what you're actually receiving?

**Comment by dikderoy** [comment]
that i am actualy getting is described on top of the issue. - multiple HTTP 100 headers before actual response headers.
expected is that I'll receive ONLY headers belonging to response itself without multiple HTTP 100 before them.

with your current code

``` php
 $headers = explode("\r\n", trim($this->_header));
            $output = array();
            $output['http_status'] = array_shift($headers);
```

it leads to wrong http_status in getHeaders() - 100 instead of actual 200.

**Comment by hackerone** [comment]
With v 1.1 this should be fixed.
Also if you want the status code please use the getStatus function.
