### ISSUE TITLE
wrong settings merge

### ISSUE THREAD

**Issue by DrDeath72** [hackerone/curl#2]
must be $this->options + $this->_config to allow rewrite default $_config options for example 
        'curl' => array(
            'class' => 'ext.Curl',
            'options' => array(
                CURLOPT_FOLLOWLOCATION => (!ini_get('open_basedir') and !ini_get('safe_mode')) ? true : false,
            ),
        ),

**Comment by hackerone** [comment]
thanks DrDeath72

applied the fix.
