### ISSUE TITLE
There is no composer.json

### ISSUE THREAD

**Issue by mariomarin** [hackerone/curl#5]
When I try to add this library with composer, I get:

```
  [Composer\Repository\InvalidRepositoryException]                                                                                   
  No valid composer.json was found in any branch or tag of https://github.com/hackerone/curl.git, could not load a package from it.  
```

**Comment by hackerone** [comment]
added composer.json

submitted the project to phundament, once they've approved it, you'll be able to use this with composer :)

http://packages.phundament.com/

**Comment by hackerone** [comment]
package added to 

https://packagist.org/

**Comment by mariomarin** [comment]
Thank you
